version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - revive
    - bodyclose
    - noctx

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    errcheck:
      exclude-functions:
        - (net.Conn).Close
        - (io.Closer).Close
        - (*net/http.Server).Shutdown
        - io.Copy
        - (*github.com/loadept/wirq/internal/server.Manager).Stop
    gosec:
      excludes:
        - G104
        - G304

  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - noctx

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
