// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function LoadConfig():Promise<config.ConfigDTO>;

export function SaveConfig(arg1:config.ConfigDTO):Promise<void>;

export function StartServer(arg1:config.ConfigDTO):Promise<void>;

export function StopServer():Promise<void>;
