// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {config} from '../models';

export function ClearLogs():Promise<void>;

export function ExportLogs(arg1:Array<number>,arg2:string):Promise<string>;

export function GetLogDetail(arg1:number):Promise<proxy.LogEntry>;

export function LoadConfig():Promise<config.ConfigDTO>;

export function SaveConfig(arg1:config.ConfigDTO):Promise<void>;

export function SelectCertFile():Promise<string>;

export function StartServer(arg1:config.ConfigDTO):Promise<void>;

export function StopServer():Promise<void>;
